debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.been.onlinestore: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always

my:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 600000
    token-prefix: "Bearer "
    header-string: Authorization

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/openapi3.yaml
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha

---

spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

my:
  jwt:
    secret: fd3fdb53thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2sdfesdfsdG9FDGsdbXRva2FyaW10b2thcwefsdtdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
